//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_сompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Policy
    {
        public int id { get; set; }
        public int Type_Insurance_Id { get; set; }
        public int User_Type_Id { get; set; }
        public int User_Id { get; set; }
        public decimal Insurance_Prize { get; set; }
        public string Insurance_Object { get; set; }
        public string Insurance_Case { get; set; }
        public decimal Insurance_Sum { get; set; }
        public System.DateTime Date_Of_Conclusion { get; set; }
        public System.DateTime Date_Of_Registration { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.DateTime Date_End { get; set; }
        public int Status { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Type_Insurance Type_Insurance { get; set; }
        public virtual User User { get; set; }
        public virtual User_Type User_Type { get; set; }
    }
}
