//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_сompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Manager
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public long Telephone_Number { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string M_Name { get; set; }
        public string Position { get; set; }
    }
}
