//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_сompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legal_User
    {
        public int User_Id { get; set; }
        public string Name { get; set; }
        public string Legal_Address { get; set; }
        public long MSRN { get; set; }
    
        public virtual User User { get; set; }
    }
}
